[theme]

# Primary accent for interactive elements
primaryColor = '#05E8BA'

# Background color for the main content area
backgroundColor = '#020275'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#A092A4'

# Color used for almost all text
textColor = '#FAFAFA'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"


